In [82]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_csv("D:/Deepl learning project/Emotion-Project/Emotions-Classification/artifacts/data_transformation/text.csv")

In [71]:
df.head()

Unnamed: 0                                               text  label
0           0                   feel realli helpless heavi heart      4
1           1  ive enjoy abl slouch relax unwind frankli need...      0
2           2               gave internship dmrg feel distraught      4
3           3                                dont know feel lost      0
4           4  kindergarten teacher thoroughli weari job take...      4

In [72]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

In [73]:
df

Unnamed: 0                                               text  label
0                0                   feel realli helpless heavi heart      4
1                1  ive enjoy abl slouch relax unwind frankli need...      0
2                2               gave internship dmrg feel distraught      4
3                3                                dont know feel lost      0
4                4  kindergarten teacher thoroughli weari job take...      4
...            ...                                                ...    ...
416804      416804  feel like tell horni devil find site suit sort...      2
416805      416805  began realiz feel agit restless would thought ...      3
416806      416806    feel curiou previou earli dawn time seek troubl      5
416807      416807  feel becuas tyran natur govern el salvador sav...      3
416808      416808  think spent time investig surround thing start...      5

[416793 rows x 3 columns]

In [74]:
df.drop("Unnamed: 0", inplace=True, axis='columns')

In [145]:
df

text  label
0                        feel realli helpless heavi heart      4
1       ive enjoy abl slouch relax unwind frankli need...      0
2                    gave internship dmrg feel distraught      4
3                                     dont know feel lost      0
4       kindergarten teacher thoroughli weari job take...      4
...                                                   ...    ...
416804  feel like tell horni devil find site suit sort...      2
416805  began realiz feel agit restless would thought ...      3
416806    feel curiou previou earli dawn time seek troubl      5
416807  feel becuas tyran natur govern el salvador sav...      3
416808  think spent time investig surround thing start...      5

[416793 rows x 2 columns]

In [76]:
df.shape

(416793, 2)

In [77]:
X = df['text']
y = df['label']

In [9]:
from src.emotion.ml.model import ModelArchitecture

In [66]:
from src.emotion import logging, ModelException
from keras.models import Sequential
from keras.optimizers import RMSprop
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import LSTM,Activation,Dense,Dropout,Input,Embedding,SpatialDropout1D
from keras import layers
from sklearn.metrics import accuracy_score, precision_recall_curve, f1_score

In [27]:
model = Sequential()
model.add(Embedding(5000,100, input_length=300))
model.add(layers.Dropout(0.5))
model.add(layers.Conv1D(128, 7, padding="valid", activation="relu", strides=3))
model.add(layers.Conv1D(128, 7, padding="valid", activation="relu", strides=3))
model.add(layers.GlobalMaxPooling1D())
model.add(layers.Dense(128, activation="relu"))
model.add(layers.Dropout(0.5))
        
        #model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(6, activation='softmax'))

d:\Deepl learning project\Emotion-Project\Emotions-Classification\venv\lib\site-packages\keras\src\layers\core\embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [28]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_6 (Conv1D)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_7 (Conv1D)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_max_pooling1d_3          │ ?                      │   0 (unbuilt) │
│ (GlobalMaxPooling1D)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:

max_words = 50000
max_len = 300

In [33]:
model = Sequential()
model.add(Embedding(max_words,100,input_length=max_len))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(1,activation='sigmoid'))
model.summary()

d:\Deepl learning project\Emotion-Project\Emotions-Classification\venv\lib\site-packages\keras\src\layers\core\embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout1d_6             │ ?                      │             0 │
│ (SpatialDropout1D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
from tensorflow.keras.models import load_model
import os
from src.emotion.utils.common import save_json, load_object
from keras.utils import pad_sequences


In [14]:
%pwd

'd:\\Deepl learning project\\Emotion-Project\\Emotions-Classification\\research'

In [15]:
os.chdir("..")

In [27]:
model = load_model("artifacts/model_evaluation/model.keras")

d:\Deepl learning project\Emotion-Project\Emotions-Classification\venv\lib\site-packages\keras\src\saving\saving_lib.py:418: UserWarning: Skipping variable loading for optimizer 'adam', because it has 22 variables whereas the saved optimizer has 2 variables. 
  trackable.load_own_variables(weights_store.get(inner_path))


In [28]:
tokenizer = load_object(file_path='artifacts/model_trainer/tokenizer.pkl')

In [130]:
text = {"text":"feel realli helpless heavi heart", "index": 0}

In [132]:
aa = pd.DataFrame(text, index=[0])

In [133]:
aa['text']

0    feel realli helpless heavi heart
Name: text, dtype: object

In [134]:
token = tokenizer.texts_to_sequences(aa['text'])


In [135]:
x = pad_sequences(token,maxlen=300)

In [136]:
pred = model.predict(x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step


In [137]:
pred

array([[4.5317656e-01, 7.9072524e-05, 4.3132586e-05, 5.6986777e-05,
        5.4664081e-01, 3.4684206e-06]], dtype=float32)

In [138]:
y_pred = np.argmax(pred,axis=1)

In [139]:
y_pred

array([4], dtype=int64)

In [109]:
a = pred.argmax(axis=1)

In [84]:
accuracy_score(y_true=y, y_pred=y_pred)

0.9323069245404794

In [85]:
y_pred

array([4, 0, 4, ..., 5, 3, 5], dtype=int64)